# 1.6: Exercises

From the last lesson, you should've created the Exceptions monad. Horray! Here it is in all its glory:

```typescript
// Types

interface V<A> {
  kind: "value",
  value: A
}

interface E {
  kind: "exception",
  exception: Error
}

type Mon<A> = V<A> | E;

// Operations

function ret<A>(x: A): Mon<A> {
  return { kind: "value", value: x }
}

function bind<A, B>(m: Mon<A>, f: (a: A) => Mon<B>): Mon<B> {
  switch (m.kind) {
    case "value":
      return f(m.value);
    case "exception":
      return m;
  }
}

function run<A>(m: Mon<A>): A {
  switch (m.kind) {
    case "value":
      return m.value;
    case "exception":
      return m.exception; // Let the program experience an uncaught exception
  }
}

function raise<A>(x: Error): Mon<A> {
  return { kind: "exception", exception: x };
}

function trywith<A>(m: Mon<A>, f: (e: Error) => Mon<A>): Mon<A> {
  switch (m.kind) {
    case "value":
      return m;
    case "exception":
      return f(m.exception);
  }
}
```

You can then put all this into a module for easy exporting and importing, just like any other library.

Using this library of sorts, how about some exercises?

**Problem 1.6.0:** Write a function `addMon` that takes two numbers, wrap them as `EMon`, and adds them. `addMon` should return an `EMon`, not a `number`.

''''problem
function addMon<A>(/* Your arguments here */): /* your return type here */ {
  // Your code here
}
//placeholder tests added below

// TESTS
// adder(2, 3) ==> 5
// adder(100, -100) ==> 0
// adder("Foo", "Bar") ==> FooBar
''''

**Problem 1.6.1:** Write a function `divideOr101` that takes in a number and does one of two things:
- If the number is 0, return 101
- Otherwise, return that number divided by 100

`divideOr101` _must_ utilize the Exception monad.

''''problem
function divideOr101(x: number): number {
  // Your code here
}
//placeholder tests added below

// TESTS
// adder(2, 3) ==> 5
// adder(100, -100) ==> 0
// adder("Foo", "Bar") ==> FooBar
''''
